In [1]:
import numpy as np
np.__version__

'1.18.0'

In [2]:
a = np.array([1,2,3,4,5])
print(type(a))
print(a)

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [3]:
b = np.array([[10,20,30],[40,50,60]])
print(b)

[[10 20 30]
 [40 50 60]]


In [4]:
a = np.zeros((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [5]:
a = np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [6]:
a = np.full((2,2), 7)
print(a)

[[7 7]
 [7 7]]


In [7]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
a = np.random.random((2,2))
print(a)

[[0.98129598 0.10230417]
 [0.74034913 0.55963402]]


In [10]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [11]:
a = np.arange(1,10,2)
print(a)

[1 3 5 7 9]


In [12]:
a = np.array(np.arange(30)).reshape((5,6))
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [13]:
a = np.array([[1,2,3],[4,5,6]])
b = a[0:2, 0:2]
print(b)


[[1 2]
 [4 5]]


In [15]:
b =a[1, :]
print(b)

[4 5 6]


In [16]:
b = a[:, 2]
print(b)

[3 6]


In [17]:
a = np.array([[1,2], [4,5], [7,8]])
b = a[[2,1],[1,0]]
print(b)

[8 4]
